export const primaryStart = "#f18a69";
export const primaryEnd = "#d13e60";
export const primaryGradientArray = [primaryStart, primaryEnd];
export const white = "#fefefe";
export const lightWhite = "#fcefe9";
export const inputPlaceholder = "#f1a895";
export const lighterWhite = "#f4e4e2";
export const circleInactive = "#ecbfbe";
export const circleActive = "#90ee90";
export const lightGreen = "#90ee90";
export const itemListText = "#555555";
export const itemListTextStrike = "#c4c4cc";
export const deleteIconColor = "#bc2e4c";

export const danger = "#bc2e4c";
export const lightGray = "#C8C8C8";
export const gray = "#555555";
export const darkGray = "#2e2e2e";
export const green = "#33B022";
